<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Zumba\\Util\\Test' => array($vendorDir . '/zumba/json-serializer/tests'),
    'Zumba\\Util' => array($vendorDir . '/zumba/json-serializer/src'),
    'Zumba\\Exception' => array($vendorDir . '/zumba/json-serializer/src'),
    'WebDriver' => array($vendorDir . '/instaclick/php-webdriver/lib'),
    'Twig_Extensions_' => array($vendorDir . '/twig/extensions/lib'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Predis' => array($vendorDir . '/predis/predis/lib'),
    'PhpOption\\' => array($vendorDir . '/phpoption/phpoption/src'),
    'PhpCollection' => array($vendorDir . '/phpcollection/phpcollection/src'),
    'PasswordLib' => array($vendorDir . '/passwordlib/passwordlib/lib'),
    'PDepend\\' => array($vendorDir . '/pdepend/pdepend/src/main/php'),
    'Native5\\Tests' => array($vendorDir . '/native5/native5-sdk-common-php/tests', $vendorDir . '/native5/native5-sdk-client-php/tests', $vendorDir . '/native5/native5-sdk-services-php/tests'),
    'Native5\\' => array($baseDir . '/lib', $baseDir . '/models'),
    'Native5' => array($vendorDir . '/native5/native5-sdk-common-php/src', $vendorDir . '/native5/native5-sdk-client-php/src', $vendorDir . '/native5/native5-sdk-services-php/src'),
    'Metadata\\' => array($vendorDir . '/jms/metadata/src'),
    'JsonSchema' => array($vendorDir . '/justinrainbow/json-schema/src'),
    'JMS\\Serializer' => array($vendorDir . '/jms/serializer/src'),
    'JMS\\' => array($vendorDir . '/jms/parser-lib/src'),
    'Illuminate\\Support' => array($vendorDir . '/illuminate/support'),
    'Illuminate\\Events' => array($vendorDir . '/illuminate/events'),
    'Illuminate\\Database' => array($vendorDir . '/illuminate/database'),
    'Illuminate\\Container' => array($vendorDir . '/illuminate/container'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
    'Goutte' => array($vendorDir . '/fabpot/goutte'),
    'Finite' => array($vendorDir . '/yohang/finite/src'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Annotations\\' => array($vendorDir . '/doctrine/annotations/lib'),
    'Codeception' => array($vendorDir . '/codeception/codeception/src'),
    'Carbon' => array($vendorDir . '/nesbot/carbon/src'),
    'Behat\\Mink\\Driver' => array($vendorDir . '/behat/mink-selenium2-driver/src', $vendorDir . '/behat/mink-browserkit-driver/src', $vendorDir . '/behat/mink-goutte-driver/src'),
    'Behat\\Mink' => array($vendorDir . '/behat/mink/src'),
    'BCC\\AutoMapperBundle' => array($vendorDir . '/bcc/auto-mapper-bundle'),
    'Akzo\\' => array($baseDir . '/lib', $baseDir . '/models'),
    '' => array($vendorDir . '/netresearch/jsonmapper/src'),
);
