<?php
namespace Akzo\Scheme;

class StateTransition {
    const STAGE_SCHEME = "_STAGE_SCHEME_";
    const UPDATE_STAGED_SCHEME = "_UPDATE_STAGED_SCHEME_";
    const INITIATE_CREATED_SCHEME = "_INITIATE_CREATED_SCHEME_";
    const INITIATE_STAGED_SCHEME = "_INITIATE_STAGED_SCHEME_";
    const REVIEW_SCHEME = "_REVIEW_SCHEME_";
    const APPROVE_SCHEME = "_APPROVE_SCHEME_";
    const REQUEST_SCHEME_UPDATE = "_REQUEST_SCHEME_UPDATE_";
    const REQUEST_SCHEME_REVIEW = "_REQUEST_SCHEME_REVIEW_";
    const UPDATE_SCHEME = "_UPDATE_SCHEME_";
    const INITIATE_UPDATED_SCHEME = "_INITIATE_UPDATED_SCHEME_";
    const EDIT_APPROVED_SCHEME = "_EDIT_APPROVED_SCHEME_";
}

